version: "3.9"
services:
  config-server:
    image: config-server:latest
    ports:
      - "8088:8088"
  twilio-service:
    image: twilio-service:latest
    ports:
      - "8092:8092"
    restart: on-failure