server:
  port: 8090

spring:
  application:
    name:
      plazoleta-service

  datasource:
    url: jdbc:mysql://database-plazoleta.ceoe9dhgx8fs.us-east-1.rds.amazonaws.com:3306/plazoleta
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8099/eureka    


jwt:
  token-validity: 86400
  secret-key: 1231rfdsfcseafa41545656fd 

appDescription: "Plazoleta service"
appVersion: "1.0.0"