server:
  port: 8091

spring:
  application:
    name:
      user-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: powerup
    password: powerup

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka    

appDescription: "User service"
appVersion: "1.0.0"
