server:
  port: 8091

spring:
  application:
    name:
      user-service
  
  datasource:
    url: jdbc:mysql://database-plazoleta.ceoe9dhgx8fs.us-east-1.rds.amazonaws.com:3306/usuarios
    username: ${RDS_USER}
    password: ${RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka    

appDescription: "User service"
appVersion: "1.0.0"
