server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: powerup
    password: powerup

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

appDescription: "User service"
appVersion: "1.0.0"
