server:
  port: 8091

spring:
  application:
    name:
      user-service
  
  datasource:
    url: jdbc:mysql://database-plazoleta.ceoe9dhgx8fs.us-east-1.rds.amazonaws.com:3306/usuarios
    username: admin
    password: pragma2023
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka    

appDescription: "User service"
appVersion: "1.0.0"
