server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: giovannileon2001

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
